# -*- coding: utf-8 -*-
"""weather app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gnz0rk7TLUI34jKni0daZZ6cVsmde1Of
"""

pip install requests

import requests

API_KEY = "b72086267fd0473fb2b134458253004 "
city = input("Enter city name: ")
url = f"http://api.weatherapi.com/v1/forecast.json?key={API_KEY}&q={city}&days=3&aqi=no&alerts=no"

response = requests.get(url)
data = response.json()

if response.status_code == 200:
    forecast_days = data['forecast']['forecastday']

    for day in forecast_days:
        print(f"\n📅 Date: {day['date']}")
        print(f"🌤️ Condition: {day['day']['condition']['text']}")
        print(f"🌡️ Max Temp: {day['day']['maxtemp_c']}°C")
        print(f"🌡️ Min Temp: {day['day']['mintemp_c']}°C")
        print(f"🌡️ Avg Temp: {day['day']['avgtemp_c']}°C")
        print("🕒 Hourly Forecast:")

        for hour in day['hour']:
            time = hour['time']
            temp = hour['temp_c']
            condition = hour['condition']['text']
            print(f"   - {time}: {temp}°C, {condition}")
else:
    print("❌ Error fetching data.")